langchain4j:
  open-ai:
    chat-model:
      max-tokens: 8192
      base-url: https://api.deepseek.com
      api-key: sk-893b1ca50b40454182a0bcdfa01fbd78
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      timeout: 300s
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-893b1ca50b40454182a0bcdfa01fbd78
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true